version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3001:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    environment:
      - WATCHPACK_POLLING=true
  test:
    build:
      context: .
      dockerfile: DockerFile.dev
    volumes:
        - /home/node/app/node_modules
        - .:/home/node/app
    command: ["npm", "run", "test"]
