name: Run Test
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker setup
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build
        run: docker build -t hellstellar/docker-learning-test -f DockerFile.dev .
        
      - name: Test
        run: docker run -e CI=true hellstellar/docker-learning-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend-docker
          environment_name: Frontend-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-834108551055
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
